services:
  mssql2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql2019
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "mystrongpassword!"
      MSSQL_PID: "Developer"
      TZ: "Asia/Seoul"
      MSSQL_AGENT_ENABLED: "true"
    volumes:
      - ./data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
